name: build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'module/**'
      - 'update.json'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'module/**'
      - 'update.json'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set variables
      id: setup
      run: |
        COMMIT_NUM=$(git rev-list --count HEAD)
        VERSION=$(jq -r .version update.json)
        ZIP_NAME=Re-Malwack_$VERSION-$COMMIT_NUM

        echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ZIP_NAME }}
        path: module/