name: Update Hosts

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every 24 hours at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-hosts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: sudo apt update && sudo apt install -y curl

      - name: Download Hosts Files
        run: |
          mkdir -p hosts
          sources=(
            "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/pro.plus-compressed.txt"
            "https://o0.pages.dev/Pro/hosts.txt"
            "https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt"
            "https://raw.githubusercontent.com/r-a-y/mobile-hosts/refs/heads/master/AdguardMobileAds.txt"
            "https://raw.githubusercontent.com/r-a-y/mobile-hosts/refs/heads/master/AdguardMobileSpyware.txt"
            "https://hblock.molinero.dev/hosts"
          )
          for url in "${sources[@]}"; do
            curl -sL "$url" >> hosts/raw_hosts.txt
            echo "" >> hosts/raw_hosts.txt  # Ensure newline separation
          done

          - name: Download Whitelist
          run: |
            curl -sL "https://raw.githubusercontent.com/ZG089/Re-Malwack/main/whitelist.txt" -o hosts/whitelist.txt
  
      - name: Clean and Merge Hosts
        run: |
            echo "Cleaning hosts..."
            sed '/^[[:space:]]*#/d; /^[[:space:]]*$/d; s/^[[:space:]]*//; s/\t/ /g; s/  */ /g' hosts/raw_hosts.txt > hosts/tmp_hosts.txt
            sort -u hosts/tmp_hosts.txt > hosts/hosts.txt
            rm -f hosts/tmp_hosts.txt  # Remove temp file
  
      - name: Remove Whitelisted Domains
        run: |
            echo "Filtering whitelist..."
            grep -vFf hosts/whitelist.txt hosts/hosts.txt > hosts/tmp_hosts.txt
            mv hosts/tmp_hosts.txt hosts/hosts.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add hosts/hosts.txt
          git commit -m "Auto-update hosts file [$(date +'%Y-%m-%d')]" || exit 0
          git push