name: Update Hosts

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-hosts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout hosts-update branch only
        uses: actions/checkout@v4
        with:
          ref: 'hosts-update'
          fetch-depth: 0

      - name: Set up dependencies
        run: sudo apt update && sudo apt install -y curl

      - name: Download and generate hosts file
        run: |
          sources=(
            "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
            "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/pro.plus.txt"
            "https://o0.pages.dev/Pro/hosts.txt"
            "https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt"
            "https://raw.githubusercontent.com/r-a-y/mobile-hosts/refs/heads/master/AdguardMobileAds.txt"
            "https://raw.githubusercontent.com/r-a-y/mobile-hosts/refs/heads/master/AdguardMobileSpyware.txt"
          )
          rm -f raw_hosts.txt whitelist.txt hosts
          for url in "${sources[@]}"; do
            curl -sL "$url" >> raw_hosts.txt
            echo "" >> raw_hosts.txt
          done
          curl -sL "https://raw.githubusercontent.com/ZG089/Re-Malwack/main/whitelist.txt" -o whitelist.txt
          sed '/^[[:space:]]*#/d; /^[[:space:]]*$/d; s/^[[:space:]]*//; s/\t/ /g; s/  */ /g' raw_hosts.txt | sort -u > hosts
          if [ -s whitelist.txt ]; then
            cp hosts hosts.bak
            while IFS= read -r domain; do
              escaped_domain=$(printf '%s' "$domain" | sed 's/[]\/$*.^|[]/\\&/g')
              sed -i "/^0\.0\.0\.0 $escaped_domain$/d" hosts
            done < whitelist.txt
            [ ! -s hosts ] && mv hosts.bak hosts
          fi

      - name: Commit and push updated hosts file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add hosts
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ "$LAST_COMMIT_MSG" == "Update hosts file" ]]; then
            git commit --amend --no-edit
            git push --force
          else
            git commit -m "Update hosts file [$(date +'%Y-%m-%d')]"
            git push
          fi